/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletAddressRouteImport } from './routes/wallet.$address'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddressRoute = WalletAddressRouteImport.update({
  id: '/wallet/$address',
  path: '/wallet/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/demo': typeof DemoRoute
  '/economy': typeof EconomyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/skills': typeof SkillsRoute
  '/wallet/$address': typeof WalletAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/demo': typeof DemoRoute
  '/economy': typeof EconomyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/skills': typeof SkillsRoute
  '/wallet/$address': typeof WalletAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/demo': typeof DemoRoute
  '/economy': typeof EconomyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/skills': typeof SkillsRoute
  '/wallet/$address': typeof WalletAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/admin'
    | '/bootstrap'
    | '/demo'
    | '/economy'
    | '/leaderboard'
    | '/skills'
    | '/wallet/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/admin'
    | '/bootstrap'
    | '/demo'
    | '/economy'
    | '/leaderboard'
    | '/skills'
    | '/wallet/$address'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/admin'
    | '/bootstrap'
    | '/demo'
    | '/economy'
    | '/leaderboard'
    | '/skills'
    | '/wallet/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRoute
  BootstrapRoute: typeof BootstrapRoute
  DemoRoute: typeof DemoRoute
  EconomyRoute: typeof EconomyRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SkillsRoute: typeof SkillsRoute
  WalletAddressRoute: typeof WalletAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$address': {
      id: '/wallet/$address'
      path: '/wallet/$address'
      fullPath: '/wallet/$address'
      preLoaderRoute: typeof WalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRoute,
  BootstrapRoute: BootstrapRoute,
  DemoRoute: DemoRoute,
  EconomyRoute: EconomyRoute,
  LeaderboardRoute: LeaderboardRoute,
  SkillsRoute: SkillsRoute,
  WalletAddressRoute: WalletAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
